# This is a basic workflow to help you get started with Actions

name: Coverage

on:
  push:
  workflow_dispatch:

jobs:
  code_coverage:
    runs-on: ubuntu-latest
    container: eltenedor/pg-no-ww:latest
    steps:
      - uses: actions/checkout@v2
      - name: Adapt configuration and run tests
        env:
            HARNESS_PERL_SWITCHES: -MDevel::Cover
        run: |
          ln -s -t /opt/webwork/ `pwd`
          mv conf/pg_defaults.yml.dist conf/pg_defaults.yml
          prove -r t
      - name: push coverage analysis
        if: always()
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: cover -report codecov

