name: pg-unit-testing
on:
  push:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      WEBWORK_ROOT: ../webwork2
    container: perl:latest
    steps:
      - name: Checkout pg repository
        uses: actions/checkout@v2
        with:
          ref: unit-test
      - name: Checkout webwork2 repository
        uses: actions/checkout@v2
        with:
          repository: openwebwork/webwork2
          ref: develop
      - name: unit test for PGauxiliaryFunctions.pl
        run: |
          cpanm Data::Dump
          prove t/macros/pgaux.t
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."
